In [6]:
import torch

# 给定的 tensor
tensor = torch.tensor([[-3.5387e-01,  5.0517e-02,  6.7984e-02, -9.3771e-01,  2.2663e-01],
                       [ 7.3542e-01,  3.1036e-01,  8.1618e-02, -6.2138e-06,  9.8852e-01], 
                       [ 7.5572e-01, -9.9732e-01, -7.9426e-01,  8.8836e-01, -8.3366e-02], 
                       [ 8.8700e-01,  2.0227e-01,  3.3193e-01, -9.6707e-01,  9.8730e-01], 
                       [-7.0735e-01, -9.7488e-01,  9.9919e-01,  9.9119e-01,  9.9997e-01], 
                       [ 5.3911e-01,  2.3677e-01,  3.4878e-01,  9.4045e-01, -9.5591e-01], 
                       [-9.9628e-01, -9.2693e-01,  9.9733e-01,  8.0266e-01, -2.0433e-01], 
                       [ 4.4628e-02,  2.1111e-01,  2.5465e-01, -9.4138e-01, -9.7344e-01], 
                       [-9.9936e-01,  5.0577e-01, -9.3955e-01,  9.7298e-01, -7.4259e-01], 
                       [ 9.1880e-01,  9.8046e-01, -9.8288e-01, -8.2905e-01, -9.2763e-01], 
                       [ 9.8788e-01, -9.9778e-01,  7.3874e-01, -9.7750e-01,  8.6473e-01]])

# 获取前两个 action
first_two_actions = tensor[:, 0]
print(first_two_actions)


tensor([-0.3539,  0.7354,  0.7557,  0.8870, -0.7074,  0.5391, -0.9963,  0.0446,
        -0.9994,  0.9188,  0.9879])


In [71]:
import torch
import torch.nn.functional as F

def process_continuous_output(output, min_val, max_val):
    scaled_output = torch.tanh(output)  # 缩放到[-1, 1]范围内
    scaled_output = 0.5 * (scaled_output + 1)  # 缩放到[0, 1]范围内
    parameter_value = min_val + (max_val - min_val) * scaled_output  # 缩放到[min_val, max_val]范围内
    return parameter_value

def process_discrete_output(output, num_values):
    probabilities = F.softmax(output, dim=-1)  # 转换为概率分布
    sampled_index = torch.multinomial(probabilities, 1)  # 从概率分布中采样一个值
    parameter_value = sampled_index.float()  # 将索引转换为浮点数
    return parameter_value

# 示例参数
min_val = 0
max_val = 10
num_values = 5

# 示例输出
continuous_output = torch.randn(1)
discrete_output = torch.randn(1, num_values)
print(discrete_output)

# 处理连续参数
processed_continuous_parameter = process_continuous_output(continuous_output, min_val, max_val)
print("Processed continuous parameter:", processed_continuous_parameter.item())

# 处理离散参数
processed_discrete_parameter = process_discrete_output(discrete_output, num_values)
print("Processed discrete parameter:", processed_discrete_parameter.item())


tensor([[-0.9477,  0.0251,  1.0918, -0.2259, -1.2759]])
Processed continuous parameter: 2.2640464305877686
Processed discrete parameter: 2.0


In [73]:
import torch

# 假设 input_data 是一个一维数组
input_data = torch.tensor([1, 2, 3, 4, 5])

# 使用 unsqueeze 将一维数组转换为二维张量
input_data_2d = input_data.unsqueeze(0)  # 在第一个维度上增加一个维度

# 检查转换后的张量维度
print("转换后的张量维度：", input_data_2d.size())

# 现在你可以将 input_data_2d 作为输入传递给 PyTorch 函数了
print(input_data_2d)

转换后的张量维度： torch.Size([1, 5])
tensor([[1, 2, 3, 4, 5]])


In [77]:
a = [[1,2,3]]
torch.tensor(a).unsqueeze(0).shape

torch.Size([1, 1, 3])

In [78]:
a = [1,2,3]
b = a
a = [23]
b

[1, 2, 3]

In [1]:
from datetime import datetime

# 获取当前日期和时间
current_datetime = datetime.now()

# 将日期和时间格式化为 'yyyy-mm-dd hh:mm:ss' 格式的字符串
formatted_datetime = current_datetime.strftime('%Y-%m-%d %H:%M:%S')

print(formatted_datetime)


2024-03-11 22:44:17


In [37]:
import torch

# 假设你有一个形状为 (1, 74) 的张量 tensor
# tensor = torch.randn(1, 74)
# tensor1 = torch.randn(1, 74)
# [tensor, tensor1]

# 通过复制tensor的第一个维度来创建一个新的张量
# new_tensor = tensor.expand(2, 74)
# new_tensor[0]

tensor = [1, 2, 3]
tensor = torch.tensor(tensor).unsqueeze(0).expand(2, -1)
tensor[0]


tensor([1, 2, 3])

In [10]:
import pandas as pd

episode_data = pd.read_excel('./res/res.xlsx')

episode_data = pd.concat(
                    [
                        episode_data,
                        pd.DataFrame(
                            {
                                "episode": [1],
                                "t": [1],
                                "reward": [1],
                                "buffersize": [1],
                            }
                        ),
                    ]
                )
episode_data

episode_data.to_excel('./res/res.xlsx', index=False)

episode_data

episode  t reward buffersize criticloss actorloss perf_tps perf_qps  \
0       1  1      1          1        NaN       NaN      NaN      NaN   

  perf_lat perf_start_tps perf_start_qps perf_start_lat  
0      NaN            NaN            NaN            NaN

In [57]:
a = [-1,1,2,3]
a[-2:]

[2, 3]

In [8]:
import mysql.connector


def get_mysql_conn(host):
    """
    host: 192.168.182.103/104
    get_state(host='192.168.182.103')
    """
    # 连接到MySQL数据库
    conn = mysql.connector.connect(
        host=host, user="hadoop", password="123456", database="test"
    )

    return conn


def get_state(conn):
    """
    获取74个state metrics
    """

    # 创建游标对象
    cursor = conn.cursor()

    try:
        # 执行SQL查询
        # cursor.execute("SHOW STATUS")

        cursor.execute(
            'SELECT NAME, COUNT from information_schema.INNODB_METRICS where status="enabled" ORDER BY NAME;'
        )

        # 获取查询结果
        result = cursor.fetchall()
        return result

    except Exception as e:
        pass

    finally:
        # 关闭游标
        cursor.close()


def close_conn(conn):
    """
    关闭数据库连接
    """
    conn.close()


conn1 = get_mysql_conn(host='192.168.182.103')
conn2 = get_mysql_conn(host='192.168.182.104')
# get_state(conn=conn1)
get_state(conn=conn2)
get_state(conn=conn2)
get_state(conn=conn2)

[('adaptive_hash_searches', 0),
 ('adaptive_hash_searches_btree', 7602),
 ('buffer_data_reads', 75074560),
 ('buffer_data_written', 4917248),
 ('buffer_pages_created', 143),
 ('buffer_pages_read', 4577),
 ('buffer_pages_written', 290),
 ('buffer_pool_bytes_data', 77332480),
 ('buffer_pool_bytes_dirty', 0),
 ('buffer_pool_pages_data', 4720),
 ('buffer_pool_pages_dirty', 0),
 ('buffer_pool_pages_free', 175488),
 ('buffer_pool_pages_misc', 16),
 ('buffer_pool_pages_total', 180224),
 ('buffer_pool_reads', 4578),
 ('buffer_pool_read_ahead', 0),
 ('buffer_pool_read_ahead_evicted', 0),
 ('buffer_pool_read_requests', 29427),
 ('buffer_pool_size', 2952790016),
 ('buffer_pool_wait_free', 0),
 ('buffer_pool_write_requests', 3116),
 ('dml_deletes', 0),
 ('dml_inserts', 0),
 ('dml_system_deletes', 55),
 ('dml_system_inserts', 55),
 ('dml_system_reads', 7774),
 ('dml_system_updates', 379),
 ('dml_updates', 0),
 ('file_num_open_files', 23),
 ('ibuf_merges', 0),
 ('ibuf_merges_delete', 0),
 ('ibuf_mer

In [2]:
res = []
a = [1, 2, 3]

res.append(a)

a = [2]

res

[[1, 2, 3]]

In [5]:
import pandas as pd

data = pd.read_excel('./res/eval_write_only.xlsx')

data.size

0

In [1]:
import time

a = time.time()
time.sleep(1)

b = time.time()

b - a

1.0007824897766113